name: Test
on:
  push:
jobs:
  full:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18, 24]
        os: [macos-latest, ubuntu-latest, windows-latest]
    name: OS ${{ matrix.os }} Node.js ${{ matrix.node }}
    steps:
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install --ci
      - name: Run unit tests
        run: npm run test
        env:
          FORCE_COLOR: 2
